# Generated by Django 2.2.7 on 2019-11-22 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('date_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('taches', models.ManyToManyField(to='btpp.Tache')),
            ],
        ),
    ]
