# Generated by Django 2.2.7 on 2019-11-22 19:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('btpp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='tache',
            name='metier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btpp.Metier'),
            preserve_default=False,
        ),
    ]
