# Generated by Django 2.2.7 on 2019-11-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btpp', '0002_auto_20191122_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='metier',
        ),
        migrations.AddField(
            model_name='tache',
            name='metier',
            field=models.ManyToManyField(to='btpp.Metier'),
        ),
    ]
