# Generated by Django 2.2.7 on 2019-11-22 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btpp', '0004_auto_20191122_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('prix', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='est_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='date_post',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='taxation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='btpp.Taxation'),
        ),
    ]
