# Generated by Django 2.2.7 on 2019-11-22 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('btpp', '0005_auto_20191122_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='lieu',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
