# Generated by Django 2.2.7 on 2019-12-02 12:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('btpp', '0007_auto_20191202_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='taxation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='btpp.Taxation'),
        ),
        migrations.AddField(
            model_name='user',
            name='abonnement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='btpp.Abonnement'),
        ),
        migrations.AddField(
            model_name='user',
            name='boite_postal',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='user',
            name='est_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='est_entreprise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='metiers',
            field=models.ManyToManyField(to='btpp.Metier'),
        ),
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quartier',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(max_length=42, null=True),
        ),
    ]
