# Generated by Django 2.2.7 on 2019-12-02 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btpp', '0008_auto_20191202_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='btpp.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='abonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='btpp.Abonnement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='metiers',
            field=models.ManyToManyField(blank=True, to='btpp.Metier'),
        ),
    ]
